"""
Edge AI Vehicle Health Monitoring System
train_model.py — Random Forest Model Trainer

Run with:  python train_model.py

This script:
  1. Reads vehicle_health.csv (generated by main.py)
  2. Encodes GOOD/BAD labels with LabelEncoder
  3. Trains a RandomForestClassifier on speed, engine_temp, vibration
  4. Evaluates accuracy, prints confusion matrix & classification report
  5. Saves vehicle_model.pkl and label_encoder.pkl
"""

import os
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
CSV_FILE    = os.path.join(BASE_DIR, "vehicle_health.csv")
MODEL_PATH  = os.path.join(BASE_DIR, "vehicle_model.pkl")
ENC_PATH    = os.path.join(BASE_DIR, "label_encoder.pkl")


def main():
    # ── 1. Load dataset ───────────────────────────────────────
    if not os.path.exists(CSV_FILE):
        raise FileNotFoundError(
            f"'{CSV_FILE}' not found.\n"
            "Run  python main.py  first to generate training data."
        )

    print(f"Reading dataset: {CSV_FILE}")
    df = pd.read_csv(CSV_FILE)
    print(f"Loaded {len(df)} rows × {df.shape[1]} columns\n")
    print(df.head())

    # ── 2. Encode target labels ───────────────────────────────
    le = LabelEncoder()
    df["health_status"] = le.fit_transform(df["health_status"])
    print(f"\nLabel encoding: {dict(zip(le.classes_, le.transform(le.classes_)))}")

    # ── 3. Feature / target split ─────────────────────────────
    features = ["speed", "engine_temp", "vibration"]
    X = df[features]
    y = df["health_status"]

    # ── 4. Train / test split ─────────────────────────────────
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )
    print(f"\nTrain: {len(X_train)} | Test: {len(X_test)}")

    # ── 5. Train Random Forest ────────────────────────────────
    print("\nTraining Random Forest Classifier ...")
    rf = RandomForestClassifier(n_estimators=100, random_state=42)
    rf.fit(X_train, y_train)

    # ── 6. Evaluate ───────────────────────────────────────────
    y_pred   = rf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"\nAccuracy : {accuracy * 100:.2f}%")
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=le.classes_))

    # ── 7. Save model + encoder ──────────────────────────────
    joblib.dump(rf, MODEL_PATH)
    joblib.dump(le, ENC_PATH)
    print(f"\nModel saved   → {MODEL_PATH}")
    print(f"Encoder saved → {ENC_PATH}")
    print("\n✅ Training complete.  Next step → python predict_live.py")


if __name__ == "__main__":
    main()
